### ISSUE TITLE
Doesn't work with Vimeo embeds on pragmaticstudio.com

### ISSUE THREAD

**Issue by benwoodward** [TanisukeGoro/Wipeyy#24]
Example: https://online.pragmaticstudio.com/tour/courses/elixir/

**Comment by TanisukeGoro** [comment]
Thanks for the Issue!
I will try to resolve it in this weekend.

**Comment by TanisukeGoro** [comment]
A video of the different domains is embedded by iframe on this site.

If the iframe's documents are not on the same domain, the Same Origin Policy prevents access to most objects and properties and will trigger access denied errors when JavaScript attempts communication.

Therefore, we probably can't resolve this problem.

**Comment by benwoodward** [comment]
Thanks for looking into it.
